### ISSUE TITLE
How do you build kramdown?

### ISSUE THREAD

**Issue by richb-hanover** [network-quality/draft-cpaasch-ippm-responsiveness#12]
On macOS (10.15.7), I tried to use `brew`, but there doesn't seem to be a built version.

As I noted elsewhere, I found https://xml2rfc.tools.ietf.org/, but this is a two-step process, which isn't easily automated into a `make` solution

**Comment by cpaasch** [comment]
Sorry, but this is not an issue for the draft here. Closing :)

People who work on IETF-drafts do have kramdown installed on their system :)
