### ISSUE TITLE
Change "tens of thousands of people"

### ISSUE THREAD

**Issue by cpaasch** [network-quality/draft-cpaasch-ippm-responsiveness#20]
Feedback from Dave Taht:

> I wanted to offer a small correction to the current RPM abstract,
> uploaded a few days ago:
> 
> https://www.ietf.org/id/draft-cpaasch-ippm-responsiveness-01.html
> 
> Millions. 3m at free alone had fq_codel on their DSL. comcast is..
> however many docsis 3.1 modems have deployed (millions) ? eero and
> everyone shipping qcom wifi chips is ? gfiber's deployment? the entire
> 3rd party firewall and router market (?) those are just the easier to
> count numbers off the top of my head. Sure, in terms of postings and
> individual interactions visible on the web in the latter case it
> doesn't seem like a lot, but I figure the existing documentation and
> user base is 1000x that....
> 
> so... millions.
> 
> If you want to also count in the upgrades in bandwidth in the last 10
> years, another accomplishment, I think, was most of that bandwidth was
> added without misguided increases in buffering, without our
> fancy-schmancy algorithms needed, so that was many more millions. If
> you want to think about server side, bbr, tsq, bql, packet pacing...
> decreases.
> 
> So a small change in language perhaps?
> 
> "semi-solved for millions of people"?
> 
> Certainly wifi and lte suck the most of what's left to fix. I
> generally say there's a billion routers left to upgrade.
> 
> One of the fantasy numbers that has kept me going for all these years
> of living on top ramen was that if aqm and fq technologies I'd worked
> on primarily... saved X users 1 second/day of waiting on the internet.
> Say X is 10m today, that's 115 days/day and depending on how you want
> to calculate that in terms of man years or time spent on the internet,
> call it 400 man years per year. Not like any of us can go cash a check
> on that karmic bank but, it's comforting.
> 
> (have a song: https://www.youtube.com/watch?v=HMG1wKpDT38 )
> 
> I tend to think that smashing latencies all through the stack affected
> pretty much the whole internet's responsiveness - that and optimizing
> web pages, cdns, etc, etc, also saved people a lot of time on waiting
> on the internet. And along the way we made webrtc go from postage
> stamp 2 frames per second in 2012 to all of civilization managing to
> cope with working from home during covid. Imagine, covid-2012?
> 
> I've never come up with a number for annoying people less...
> 
> Blocking ads is still effective for saving time however, another
> annoyance that's cropped up in the last few years is the teaser
> paragraph and then
> the demand to turn off advertising on a per site basis. I wish there
> was a plugin for a browser that blocked content from paywall demanding
> sites.
> I'm glad I can pay google/pandora/netflix 10 bucks a month for
> streaming services without ads.
> 
> Anyway, just the deployed aqm/fq solutions alone are in the 10s of
> millions, IMHO. Just working so well for those using them that they
> never noticed.
> 
> -- 
> Fixing Starlink's Latencies: https://www.youtube.com/watch?v=c9gLo6Xrwgw
> 
> Dave Täht CEO, TekLibre, LLC
> _______________________________________________
> Rpm mailing list
> Rpm@lists.bufferbloat.net
> https://lists.bufferbloat.net/listinfo/rpm

**Comment by dtaht** [comment]
Groovy.

There are other ways to calculate the saved value of reducing
latencies on the internet that someone could explore that result
in much bigger and ego-swelling value, that I try not to think about
much. I'm content with 1sec a day!!, but...

Take drops/day for example. On the network that I used to maintain at
the campground, those were about 3000-9000/day (about 5% marks also)
for 3-30 active users, and I knew each of those was preventing a
600+ms (or 240+ms) latency excursion that might have lasted for
seconds or minutes for all the other users, and a network that pretty
consistently carried voip and videoconferencing well (except on the
farthest reaches of the wifi).

A number I keep in my head is loading slashdot took 4 minutes with
1sec latency, 14s with none.

Reschedules were much, much higher, (and not a particularly accurate
measure) so every time fq is invoked you save the time of the length
of the rest of the queue.

Then of course you have the enormous apple deployment of fq_"codel",
interleaving away... the linux cloud deployment, the chromebook
deployment....

It would be kind of cool to somehow total up an estimate of how
valuable the whole bufferbloat.net effort has been to the internet as
a whole. What if jim had NOT looked up from his scp to MIT that day
and started asking questions?

**Comment by dtaht** [comment]
anyway, it's somehow expressing that the routers are the only thing major left to upgrade, rather than me ranting about millions and billions of fixes elsewhere, that was more on my mind.

**Comment by cpaasch** [comment]
fixed with https://github.com/network-quality/draft-cpaasch-ippm-responsiveness/commit/cadc6102d4951b2262ff54c9cd9f431fecf516b4
