### ISSUE TITLE
Define canonical ranges for RPM measurements

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-cpaasch-ippm-responsiveness#24]
I hope that this is a valid question/comment. I am thankful for the work that you have done with this draft!

Along the numerical result of its calculation, the macOS `networkQuality` client "describes" the RPM measurement (e.g., `Responsiveness: Medium (234 RPM)`. It seems like a good idea for this standard to define the mapping between RPM and adjective so that all users of the protocol can communicate their results consistently and without ambiguity.

I would assume that such a mapping exists within the source code for `networkQuality` and could be imported directly into the draft. 

Again, I hope that this is valid and not a waste of your time!
Will

cc @cpaasch @randall

**Comment by hawkinsw** [comment]
Looking through the `strings` output for the networkQuality dylib, it looks like there are three possible buckets:

```
Medium
High
Unqualified
```

**Comment by cpaasch** [comment]
Fixed with: https://github.com/network-quality/draft-cpaasch-ippm-responsiveness/commit/0852917ac9bc49682af88df18688883d5b0bc25f
