### ISSUE TITLE
What happens if the conditions for saturation are not met within 20 seconds?

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-cpaasch-ippm-responsiveness#25]
Hello again!

As I said before, I hope that this is a meaningful/helpful comment/question: What happens if the conditions for saturation are not met within 20 seconds?

While not likely, it is possible that the client cannot saturate a user's connection according to the algorithm (in Section 4.1) in a fixed amount of time. Because one of the goals of the standard is to create a metric that can be measured quickly (`Our target is 20 seconds.`), it seems like a good idea for the standard to a) specify a time limit for the test and b) specify what happens if that time limit is exceeded. 

For the client I am writing, I have adopted this practice:
1. The client attempts to saturate the connection for a fixed period of time (user defined from the CLI with a default of 20 seconds) using the algorithm described in Section 4.1.
2. If the client cannot saturate the connection within that time, the connection is considered _provisionally_ saturated and measurement of RPM proceeds as if the connection is _actually_ saturated.
3. The client gets another 5 seconds (the user cannot change this value) to perform the series of probes described in Section 4.1 and calculate the RPM.

This, of course, is not to say that this is the best idea. Nor may it even be a good idea. I'm new to this whole process and it takes me a while to get my wheels spinning (get it?).

I hope this is helpful!
Will

cc @randall @cpaasch

**Comment by hawkinsw** [comment]
Searching through the `strings` output of the dylib for networkQuality, it looks like the client already takes this into account: 

```
not reached
reached naturally
reached by timeout
saturation reason unknown
```

**Comment by cpaasch** [comment]
@hawkinsw  - I have a PR for this at https://github.com/network-quality/draft-cpaasch-ippm-responsiveness/pull/26

Please let me know your thoughts!

**Comment by hawkinsw** [comment]
As they say on the internet, LGTM.

I did look up whether it is "time frame", "time-frame" or "timeframe" and
found this: https://www.merriam-webster.com/dictionary/time%20frame#note-1
Not sure whether you want to heed that advice or not. Completely up to you!

Will
