### ISSUE TITLE
Include Discussion of Expected Operational Scenarios

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-cpaasch-ippm-responsiveness#28]
From IPPM adoption call feedback:

  * There may be no bottleneck buffer - the test/metric needs to detect that and act appropriate.
  * One might be interested in the metric while the test adds an insignificant load only. While receiver tries to consume service X, what's the metric seen from Y?
     (may help to clarify, whether the access causes trouble or another network section).

**Comment by cpaasch** [comment]
For completeness, here is my reply:

> > Some comments:
> > - I'd appreciate if the draft was covering expectable operational scenarios, namely
> > * There may be no bottleneck buffer - the test/metric needs to detect that and act appropriate.
> > 
> 
> I'm not sure what you mean ? Every flow is limited by some bottleneck that sits somewhere. Sometimes, it's the last mile, sometimes it's the Wi-Fi connectivity, sometimes flows become CPU-limited. But there always is a bottleneck somewhere that is limiting things at which point a buffer is building up (even though that "buffer" may be just 1 packet large)
> 
> > * One might be interested in the metric while the test adds an insignificant load only. While receiver tries to consume service X, what's the metric seen from Y? 
> >    (may help to clarify, whether the access causes trouble or another network section).
> > 
> 
> That would indeed be interesting for trouble-shooting and debugging. I believe this is out-of-scope though.
>

**Comment by cpaasch** [comment]
I believe these points have been discussed and no changes will be made.
