### ISSUE TITLE
Server-based RPM measurement in scope or not?

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-cpaasch-ippm-responsiveness#29]
From IPPM adoption call feedback:

- Measuring the maximum RPM as seen from the test server is part of the test or it isn't? That's not clear to me by now.
  I'm favouring to make measuring the maximum RPM part of the test, this may help to scale results.

**Comment by cpaasch** [comment]
My reply:

> > - Measuring the maximum RPM as seen from the test server is part of the test or it isn't? That's not clear to me by now.
> > I'm favouring to make measuring the maximum RPM part of the test, this may help to scale results.
> > 
> 
> The methodology defines to only measure from the client as we are interested in responsiveness as a metric that is (as close as possible) representative of an end-user experience.
> 
> When you say "maximum RPM", do you mean that on an "idle" network?

**Comment by cpaasch** [comment]
Server-side view is out-of-scope.
