### ISSUE TITLE
Preventing DDoS

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-cpaasch-ippm-responsiveness#30]
From IPPM adoption call feedback:

How will the servers handle the possibility of a DDoS?

**Comment by cpaasch** [comment]
Reply:

> > - The test set-up should prevent application as DoS attack tool.
> 
> 
> The json-fetch at the beginning of the test allows server-side CDN deployments to "rate-limit" clients by simply delaying the response to the json-fetch.
> 
> What else do you have in mind regarding a DoS attack tool?

**Comment by cpaasch** [comment]
I don't think this needs to be discussed in a draft. It's a CDN-deployment issue.
