### ISSUE TITLE
Hidden Assumption: Bandwidth is fixed

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-cpaasch-ippm-responsiveness#32]
From @gregmirsky on the IPPM adoption call feedback:

> It seems like in the foundation of the methodology described in the draft lies the assumption that without adding new flows the available bandwidth is constant, does not change. While that is mostly the case, there are technologies that behave differently and may change bandwidth because of the outside conditions. Some of these behaviors of links with variable discrete bandwidth are discussed in, for example, RFC 8330 and RFC 8625.

**Comment by cpaasch** [comment]
Copy-pasting my reply:

> > It seems like in the foundation of the methodology described in the draft lies the assumption that without adding new flows the available bandwidth is constant, does not change. While that is mostly the case, there are technologies that behave differently and may change bandwidth because of the outside conditions. Some of these behaviors of links with variable discrete bandwidth are discussed in, for example, RFC 8330 and RFC 8625.
> 
> 
> I'm not sure I entirely understand your comment. But let me explain why we are gradually adding new flows:
> 
> 1. TCP-implementations have usually a fixed limit for the upper bound of the receive window. In some networks that upper bound is lower than the BDP of the network. Thus, the only way to reach full capacity is by having multiple flows.
> 2. Having multiple connections allows to quicker achieve full capacity in high-RTT networks and thus speeds up the test-duration.
> 3. In some networks with "random" packet-loss, congestion-control may come in the way of achieving full capacity. Again, multiple flows will work around that.
>

**Comment by cpaasch** [comment]
Remainder of the exchange:

> GIM>> I might have asked several questions at once. Let me clarify what I am looking for:
> As I understand the method of creating the "working conditions in a network" is based on certain assumptions. First, seems is that the bandwidth is symmetrical between the measurement points. Second, that the bandwidth doesn't change for the duration of the measurement session. AFAIK, in the access networks, both are not necessarily always the case.
> We don't have the assumption that bandwidth is symmetrical (assuming, you mean uplink/downlink symmetry - please clarify otherwise).
> 
> The load-generating algorithm runs independently for uplink and downlink traffic. And it is perfectly fine when both have huge asymmetry.
> 
> 
> Regarding the stability of the bandwidth:
> You are making a good point indeed that we assume that the bandwidth is to some extend stable while ramping up the flows to "working conditions". Admittedly that assumption does not always hold, and that is one of the reasons why we try hard for the test to not take too long.
> I'm not sure how we could adjust the algorithm for varying bandwidth without introducing too much complexity. I'm open for suggestions :-)


 We did not decide to makes changes, thus closing the issue.
