### ISSUE TITLE
Clarify value of using timeless units to express responsiveness

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-cpaasch-ippm-responsiveness#33]
From @gregmirsky on IPPM adoption call feedback: 

>     Then, I find the motivation not to use time units to express the responsiveness metric not convincing:
       "Latency" is a poor measure of responsiveness, since it can be hard
       for the general public to understand.  The units are unfamiliar
       ("what is a millisecond?") and counterintuitive ("100 msec - that
       sounds good - it's only a tenth of a second!").

**Comment by cpaasch** [comment]
To be discussed.

**Comment by cpaasch** [comment]
The entire exchange:

> > > > Then, I find the motivation not to use time units to express the responsiveness metric not convincing:
> > > >    "Latency" is a poor measure of responsiveness, since it can be hard
> > > >    for the general public to understand.  The units are unfamiliar
> > > >    ("what is a millisecond?") and counterintuitive ("100 msec - that
> > > >    sounds good - it's only a tenth of a second!").
> > > 
> > > Can you expand on what exactly is not convincing to you? Do you think that people will mis-understand the metric or that milli-seconds is the right way to communicate responsiveness to the general public?
> > GIM>> Let me try. We know packet delay requirements for AR, VR applications. I believe that gamers are familiar with these numbers too. The same is likely the case for the industrial automation use cases served, for example, by Deterministic Networking.
> > 
> I can understand that for a technical audience, milli-seconds is easy and familiar. A non-technical audience might be more open to accepting a new "higher-is-better" metric. Responsiveness is something new and abstract so, it's kind of natural that it comes with a new unit.
> 
> But I fully recognize that that's a controversial topic and can be discussed at length :)

I will add a conversion table in the draft (#18). That may help a bit.

**Comment by moeller0** [comment]
timeless unit? IMHO per minute clearly implies time, no? As commented in #18 I think optionally reporting the delays as interval instead of a rate is desirable, but that could be guarded behind an `--give-me-the-details` command line switch.

**Comment by hawkinsw** [comment]
Great feedback!! Thank you!!

Will
